parameters:
    app.site_title: 'Gestion Pharmacie'
    app.name: 'Pharmacie App'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\AuthService:
        arguments:
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.password_hasher'
            $security: '@security.helper'

    App\Service\UserService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.password_hasher'

    App\Models\Repository\UserRepository:
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - App\Models\Entity\User

    App\Repository\:
        resource: '../src/Repository'
        arguments:
            $registry: '@doctrine'

    App\Twig\:
        resource: '../src/Twig/'
        tags: ['twig.extension']

    App\EventListener\SecurityListener:
        arguments:
            $security: '@security.helper'
            $urlGenerator: '@router'
            $logger: '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }
            - { name: monolog.logger, channel: security }

    App\Repository\UserRepository:
        arguments:
            $registry: '@doctrine'
            $passwordHasher: '@security.password_hasher'

    App\Security\UserVoter:
        tags: ['security.voter']

    App\Service\FlashService:
        arguments:
            $requestStack: '@request_stack'

    App\Twig\AppExtension:
        arguments:
            $urlGenerator: '@router'
            $security: '@security.helper'
        tags: ['twig.extension']

    App\Twig\AssetExtension:
        tags: ['twig.extension']

    App\Security\AuthenticationSuccessHandler:
        arguments:
            $logger: '@logger'
            $security: '@security.helper'
            $urlGenerator: '@router'
        tags: ['security.authentication.success_handler']

    App\Service\OrdonnanceService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\FactureService:
        arguments:
            $mongoUrl: '%env(MONGODB_URL)%'
            $databaseName: '%env(MONGODB_DB)%'

    form.factory:
        class: Symfony\Component\Form\FormFactory
        arguments: ['@form.registry']